use std::fs;

use crate::engine::feedback::OperationResult;

use super::run_cmd;

/// Partition a disk with GPT and a single primary partition.
/// Runs `partprobe` and `udevadm settle` afterward so the kernel picks up the
/// new partition table and the partition device node (e.g. `/dev/sda1`) exists
/// before any subsequent mkfs call.
pub fn partition_disk(device: &str) -> OperationResult {
    if let Err(e) = run_cmd(
        "parted",
        &["-s", device, "mklabel", "gpt", "mkpart", "primary", "1MiB", "100%"],
    ) {
        return OperationResult::Error(format!("failed to partition {}: {}", device, e));
    }

    // Re-read partition table
    let _ = run_cmd("partprobe", &[device]);
    let _ = run_cmd("udevadm", &["settle", "--timeout=5"]);

    OperationResult::Success
}

/// Return the first partition device path for a disk.
/// NVMe devices use a `p` separator (e.g. `nvme0n1p1`), while SCSI/virtio/IDE
/// devices append the number directly (e.g. `sda1`).
pub fn partition_path(device: &str) -> String {
    let base = device.rsplit('/').next().unwrap_or(device);
    if base.starts_with("nvme") || base.starts_with("mmcblk") || base.starts_with("loop") {
        format!("{}p1", device)
    } else {
        format!("{}1", device)
    }
}

/// Create a btrfs filesystem on one or more devices.
/// Automatically converts raw disk paths to their first partition path.
pub fn mkfs_btrfs(devices: &[String]) -> OperationResult {
    let part_devices: Vec<String> = devices.iter().map(|d| partition_path(d)).collect();
    let mut args = vec!["-f"];
    let dev_refs: Vec<&str> = part_devices.iter().map(|d| d.as_str()).collect();
    args.extend(dev_refs);

    match run_cmd("mkfs.btrfs", &args) {
        Ok(_) => OperationResult::Success,
        Err(e) => OperationResult::Error(format!(
            "mkfs.btrfs failed on {}: {}",
            part_devices.join(", "),
            e
        )),
    }
}

/// Create a btrfs subvolume.
pub fn create_btrfs_subvolume(mount_point: &str, name: &str) -> OperationResult {
    let subvol_path = format!("{}/{}", mount_point, name);
    match run_cmd("btrfs", &["subvolume", "create", &subvol_path]) {
        Ok(_) => OperationResult::Success,
        Err(e) => OperationResult::Error(format!(
            "failed to create btrfs subvolume {}: {}",
            subvol_path, e
        )),
    }
}

/// Mount a filesystem at the given mount point, creating the directory if needed.
/// For btrfs, runs `btrfs device scan` first so RAID members are discovered.
pub fn mount_filesystem(device: &str, mount_point: &str, fs_type: &str) -> OperationResult {
    if let Err(e) = fs::create_dir_all(mount_point) {
        return OperationResult::Error(format!(
            "failed to create mount point {}: {}",
            mount_point, e
        ));
    }

    // For btrfs RAID arrays, scan for member devices before mounting
    if fs_type == "btrfs" {
        let _ = run_cmd("btrfs", &["device", "scan"]);
    }

    match run_cmd("mount", &["-t", fs_type, device, mount_point]) {
        Ok(_) => OperationResult::Success,
        Err(e) => OperationResult::Error(format!(
            "failed to mount {} at {}: {}",
            device, mount_point, e
        )),
    }
}

/// Generate /etc/fstab in the installed system so the root filesystem
/// is mounted correctly on boot. Without this, systemd may fail to
/// auto-generate a mount unit for paths with special characters (like hyphens).
pub fn generate_fstab(mount_point: &str, device: &str, fs_type: &str) -> OperationResult {
    let fstab_dir = format!("{}/etc", mount_point);
    if let Err(e) = fs::create_dir_all(&fstab_dir) {
        return OperationResult::Error(format!("failed to create {}: {}", fstab_dir, e));
    }

    let fstab_path = format!("{}/fstab", fstab_dir);
    // Read existing fstab if present
    let existing = fs::read_to_string(&fstab_path).unwrap_or_default();

    let entry = format!(
        "# Generated by ttyforce\n{}\t/\t{}\tdefaults,subvol=@\t0\t1\n",
        device, fs_type
    );

    // Remove any previous ttyforce entries, then append ours
    let filtered: String = existing
        .lines()
        .filter(|l| !l.contains("# Generated by ttyforce"))
        .filter(|l| !(l.starts_with(device) && l.contains("subvol=@")))
        .collect::<Vec<_>>()
        .join("\n");
    let new_content = if filtered.trim().is_empty() {
        entry
    } else {
        format!("{}\n{}", filtered.trim_end(), entry)
    };
    if let Err(e) = fs::write(&fstab_path, new_content) {
        return OperationResult::Error(format!("failed to write {}: {}", fstab_path, e));
    }

    OperationResult::Success
}

/// Recursively unmount a mount point. Best-effort: returns Success even on
/// failure since the mount may not exist.
pub fn cleanup_unmount(mount_point: &str) -> OperationResult {
    let _ = run_cmd("umount", &["-R", mount_point]);
    OperationResult::Success
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_fstab() {
        let tmp = std::env::temp_dir().join("ttyforce-fstab-test");
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();

        let result = generate_fstab(tmp.to_str().unwrap(), "/dev/sda1", "btrfs");
        assert!(result.is_success(), "generate_fstab failed: {:?}", result);

        let fstab = std::fs::read_to_string(tmp.join("etc/fstab")).unwrap();
        assert!(fstab.contains("/dev/sda1"), "fstab missing device");
        assert!(fstab.contains("btrfs"), "fstab missing fs_type");
        assert!(fstab.contains("subvol=@"), "fstab missing subvol option");

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn test_generate_fstab_idempotent() {
        let tmp = std::env::temp_dir().join("ttyforce-fstab-idem-test");
        let _ = std::fs::remove_dir_all(&tmp);
        std::fs::create_dir_all(&tmp).unwrap();

        generate_fstab(tmp.to_str().unwrap(), "/dev/sda1", "btrfs");
        generate_fstab(tmp.to_str().unwrap(), "/dev/sda1", "btrfs");

        let fstab = std::fs::read_to_string(tmp.join("etc/fstab")).unwrap();
        let count = fstab.matches("/dev/sda1").count();
        assert_eq!(count, 1, "fstab should have exactly one entry, got:\n{}", fstab);

        let _ = std::fs::remove_dir_all(&tmp);
    }

    #[test]
    fn test_partition_path_scsi() {
        assert_eq!(partition_path("/dev/sda"), "/dev/sda1");
        assert_eq!(partition_path("/dev/sdb"), "/dev/sdb1");
    }

    #[test]
    fn test_partition_path_nvme() {
        assert_eq!(partition_path("/dev/nvme0n1"), "/dev/nvme0n1p1");
    }

    #[test]
    fn test_partition_path_mmcblk() {
        assert_eq!(partition_path("/dev/mmcblk0"), "/dev/mmcblk0p1");
    }

    #[test]
    fn test_partition_path_virtio() {
        assert_eq!(partition_path("/dev/vda"), "/dev/vda1");
    }
}

/// Set up btrfs with RAID.
/// Automatically converts raw disk paths to their first partition path.
pub fn btrfs_raid_setup(devices: &[String], raid_level: &str) -> OperationResult {
    let part_devices: Vec<String> = devices.iter().map(|d| partition_path(d)).collect();
    let mut args = vec!["-f", "-d", raid_level, "-m", raid_level];
    let dev_refs: Vec<&str> = part_devices.iter().map(|d| d.as_str()).collect();
    args.extend(dev_refs);

    match run_cmd("mkfs.btrfs", &args) {
        Ok(_) => OperationResult::Success,
        Err(e) => OperationResult::Error(format!(
            "btrfs raid setup ({}) failed on {}: {}",
            raid_level,
            part_devices.join(", "),
            e
        )),
    }
}
